data:
  database_path: datasets/BBDD/
  query_path: datasets/qsd1_w3/

retrieval:
  color_space_list: [lab]
  preprocesses_list: [clahe]
  masking: false
  denoising: true

  descriptors_list: [hist]
  bins_list: [16]
  blocks_list: [8]
  hist_dims_list: [1]

  distances_list: [x2]

  k_list: [10]

evaluation:
  val: true
