median:
  median_kernel_size: [3, 5, 7, 9, 11]

gaussian:
  gaussian_kernel_size: [3, 5, 7, 9, 11]
  gaussian_sigma: [1, 3, 5, 7, 9]

bilateral:
  bilateral_kernel_size: [3, 5, 7, 9, 11]
  bilateral_sigma: [1, 3, 5, 7, 9]

nlm:
  nlm_h: [5, 10, 20]
  nlm_hcolor: [5, 10, 20]
  nlm_template_window_size: [3, 7, 11]
  nlm_search_window_size: [17, 21, 25]

wavelets:
  wavelet: ['bior', 'rbio']
  wavelet_threshold: [0.25, 0.50, 0.75, 0.90]
  wavelet_mode: ['soft', 'hard', 'garrote', 'less']