data:
  database_path: datasets/BBDD/
  query_path: datasets/qsd2_w3/

retrieval:
  color_space_list: [lab, gray_scale]
  preprocesses_list: ['', clahe]
  masking: true
  denoising: true

  descriptors_list: [wavelet]
  bins_list: [16, 32]
  blocks_list: [4, 8]
  hist_dims_list: [1]           
  
  wavelets_list: ['bior1.1','bior3.1','rbio1.1','rbio3.1', 'db2', 'db4']
  wavelets_levels_list: [1, 2, 3, 4]

  distances_list: [euclidean, l1, x2, hist_intersection, hellinger, canberra]
  
  k_list: [1]

evaluation:
  val: true
