data:
  database_path: datasets/BBDD/
  query_path: datasets/qsd2_w3/

retrieval:
  color_space_list: [gray_scale]
  preprocesses_list: ['']
  masking: true
  denoising: true

  descriptors_list: [DCT]
  
  blocks_list: [4]
  DCT_coeffs_list: [16]
  
  distances_list: [canberra]
  k_list: [1]

evaluation:
  val: false

output:
  pickle_filename: 'results/w3_sample.pkl'

