data:
  database_path: ../BBDD/
  query_path: ../qsd1_w3/

retrieval:
  color_space_list: [lab, hsv]
  preprocesses_list: ['', clahe]

  descriptors_list: [DCT]
  blocks_list: [4,8]
  hist_dims_list: [1]            
  DCT_coeffs_list: [4, 8, 16]
  distances_list: [euclidean, l1, x2, hist_intersection, hellinger, canberra]
  wavelets_list: ['bior1.1','bior3.1','rbio1.1','rbio3.1']
  k_list: [1]

evaluation:
  val: true
