data:
  database_path: ../BBDD/
  query_path: ../qsd1_w3/

retrieval:
  color_space_list: [lab, hsv]
  preprocesses_list: ['', clahe]

  descriptors_list: [wavelet]
  bins_list: [16]
  blocks_list: [4]
  hist_dims_list: [1]            
  DCT_coeffs_list: [4, 8, 16]
  LBP_scales_list:
  - [8, 1.0]
  - [10, 2.5]
  distances_list: [euclidean, l1, x2, hist_intersection, hellinger, canberra]
  wavelets_list: ['bior1.1','bior3.1','rbio1.1','rbio3.1']
  k_list: [1]

evaluation:
  val: true
