median:
  median_kernel_size: [3, 5, 7, 9, 11]

gaussian:
  gaussian_kernel_size: [3, 5, 7, 9, 11]
  gaussian_sigma: [1, 3, 5, 7, 9]

bilateral:
  bilateral_kernel_size: [3, 5, 7, 9, 11]
  bilateral_sigma: [1, 3, 5, 7, 9]

nlm:
  nlm_h: [5, 10, 15, 20, 25]
  nlm_hcolor: [5, 10, 15, 20, 25]
  nlm_template_window_size: [3, 5, 7, 9, 11]
  nlm_search_window_size: [17, 19, 21, 23, 25]

wavelets:
  wavelet: ['haar', 'db', 'bior', 'rbio']
  wavelet_threshold: [0.15, 0.30, 0.45, 0.60, 0.75, 0.90]
  wavelet_mode: ['soft', 'hard', 'garrote', 'greater', 'less']