# Rutas
database: "../BBDD"
dataset: "../qsd1_w4"

# AKAZE
kp_descriptor: ["akaze"]
descriptor_size: [0]        # 0 = full size for MLDB
descriptor_channels: [3]    # typically 1, 2, or 3 for MLDB
threshold: [0.0001]        # detection threshold
n_octaves: [10]
n_octave_layers: [10]

# MAP@K a evaluar
k: [1,5]

# Modo y salida
mode: "search"
output_csv: "./grid_search_sift.csv"

