# Rutas
database: "datasets/BBDD"
dataset: "datasets/qsd1_w4"

# AKAZE
kp_descriptor: ["akaze"]
descriptor_size: [0]        # 0 = full size for MLDB
descriptor_channels: [3]    # typically 1, 2, or 3 for MLDB
threshold: [0.001]        # detection threshold
n_octaves: [4]
n_octave_layers: [4]

# Matcher
lowe_ratio: [0.75]
min_good: [20]
match_distance: ['hamming']

# MAP@K a evaluar
k: [1,5]

# Modo y salida
mode: "search"
output_csv: "./akaze_test2.csv"

