# Rutas
database: "datasets/BBDD"
dataset: "datasets/qsd1_w4"

# AKAZE
kp_descriptor: ["akaze"]
descriptor_size: [0]        # 0 = full size for MLDB
descriptor_channels: [3]    # typically 1, 2, or 3 for MLDB
threshold: [0.0001]        # detection threshold
n_octaves: [8]
n_octave_layers: [8]

# MAP@K a evaluar
k: [1]

lowe_ratio: [0.75]
min_good: [10]
match_distance: ['hamming']

# Modo y salida
mode: "search"
output_csv: "./akaze_test.csv"

