#Rutas
database: "datasets/BBDD"
dataset: "datasets/qsd1_w4"

kp_descriptor: ["sift", "akaze", "orb"]
#SIFT

n_features: [500, 800]
edge_threshold: [5, 10]
n_octave_layers: [2, 4]
contrast_threshold: [0.01, 0.02]
sigma: [1.2, 1.6]

#ORB

scale_factor: [1.1, 1.2]
n_levels: [6, 8]
first_level: [0]
WTA_K: [2, 3, 4]
patch_size: [31, 41]
fast_threshold: [10, 20, 30]

#AKAZE

descriptor_size: [0] # 0 = full size for MLDB
descriptor_channels: [3] # typically 1, 2, or 3 for MLDB
threshold: [0.001, 0.005, 0.0001] # detection threshold
n_octaves: [4, 8]
n_octave_layers: [4, 8]

# Matchers
lowe_ratio: [0.25, 0.5, 0.75, 1.0]
min_good: [5, 10, 15, 20, 50, 100]
match_distance: ["l2", "l2sqr"]

#MAP@K a evaluar

k: [1]

# Modo y salida
mode: "search"
output_csv: "./grid_search_sift.csv"