# Rutas
database: "../BBDD"
dataset: "../qsd1_w4"

# SIFT
kp_descriptor: ["orb"]
n_features: [500]
edge_threshold: [10]
n_octave_layers: [4]
contrast_threshold: [0.02]
sigma: [1.6]

# ORB
scale_factor: [1.2]
n_levels: [8]
first_level: [0]
WTA_K: [3]
patch_size: [31]
fast_threshold: [20]

# MAP@K a evaluar
k: [1,5]

# Modo y salida
mode: "search"
output_csv: "./grid_search_sift.csv"
